apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/fastapi-docker-traefik-default: "true"
        io.kompose.service: traefik
    spec:
      containers:
        - image: traefik:v2.9.6
          name: traefik
          ports:
            - containerPort: 80
              hostPort: 8008
              protocol: TCP
            - containerPort: 8080
              hostPort: 8081
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/traefik/traefik.toml
              name: traefik-claim0
            - mountPath: /var/run/docker.sock
              name: traefik-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: traefik-claim0
          persistentVolumeClaim:
            claimName: traefik-claim0
        - name: traefik-claim1
          persistentVolumeClaim:
            claimName: traefik-claim1
            readOnly: true
status: {}
